#Expyriment 0.11.dev5 (Python 3.11.9), .xpe-file, coding: cp1252
#date: Wed Feb 12 2025 14:18:25
#sha1: 634239
#modules: generateSubjectCsv.py (dda15b)
#display: size=(800, 600), window_mode=False, opengl=2
#os: uname_result(system='Windows', node='Geoff3', release='10', version='10.0.26100', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
5888,stderr,received,'Traceback (most recent call last):'
5888,stderr,received,'  File "C:\\Users\\ali_a\\Desktop\\Single_Word_Processing_Stage\\Single_Word_Processing\\Localizer\\Code\\runVisualCategory.py", line 127, in <module>'
5889,stderr,received,'    bs = stimuli.Picture(os.path.join(STIM_DIR,'
5889,stderr,received,'         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
5890,stderr,received,'  File "C:\\Users\\ali_a\\Desktop\\Single_Word_Processing_Stage\\.venv\\Lib\\site-packages\\expyriment\\stimuli\\_picture.py", line 43, in __init__'
5893,stderr,received,'    raise IOError(u"The picture file \'{0}\' does not exist".format('
5893,stderr,received,"OSError: The picture file 'STIM_DIR\\stimblank.png' does not exist"
