#Expyriment 0.11.dev5 (Python 3.11.9), .xpe-file, coding: cp1252
#date: Mon Mar 17 2025 18:03:24
#sha1: 65d311
#modules: generateSubjectCsv.py (dda15b)
#display: size=(800, 600), window_mode=False, opengl=2
#os: uname_result(system='Windows', node='Geoff3', release='10', version='10.0.26100', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
5272,stderr,received,'Traceback (most recent call last):'
5273,stderr,received,'  File "C:\\Users\\ali_a\\Desktop\\Single_Word_Processing_Stage\\Single_Word_Processing\\Localizer\\Code\\runVisualCategory.py", line 201, in <module>'
5274,stderr,received,'    mappict[picture] = stimuli.Picture(os.path.join('
5275,stderr,received,'                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
5275,stderr,received,'  File "C:\\Users\\ali_a\\Desktop\\Single_Word_Processing_Stage\\.venv\\Lib\\site-packages\\expyriment\\stimuli\\_picture.py", line 43, in __init__'
5276,stderr,received,'    raise IOError(u"The picture file \'{0}\' does not exist".format('
5277,stderr,received,"OSError: The picture file 'C:\\Users\\ali_a\\Desktop\\Single_Word_Processing_Stage\\Single_Word_Processing\\Localizer\\Stimuli\\Images\\wordF02.png' does not exist"
